/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetBarRouteImport } from './routes/widget.bar'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicVerifyInstallRouteImport } from './routes/api/public/verify-install'
import { Route as ApiPublicWidgetPickRouteImport } from './routes/api/public/widget.pick'
import { Route as ApiPublicWidgetClickRouteImport } from './routes/api/public/widget.click'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetBarRoute = WidgetBarRouteImport.update({
  id: '/widget/bar',
  path: '/widget/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicVerifyInstallRoute = ApiPublicVerifyInstallRouteImport.update({
  id: '/api/public/verify-install',
  path: '/api/public/verify-install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetPickRoute = ApiPublicWidgetPickRouteImport.update({
  id: '/api/public/widget/pick',
  path: '/api/public/widget/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetClickRoute = ApiPublicWidgetClickRouteImport.update({
  id: '/api/public/widget/click',
  path: '/api/public/widget/click',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/widget/bar': typeof WidgetBarRoute
  '/api/public/verify-install': typeof ApiPublicVerifyInstallRoute
  '/api/public/widget/click': typeof ApiPublicWidgetClickRoute
  '/api/public/widget/pick': typeof ApiPublicWidgetPickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/widget/bar': typeof WidgetBarRoute
  '/api/public/verify-install': typeof ApiPublicVerifyInstallRoute
  '/api/public/widget/click': typeof ApiPublicWidgetClickRoute
  '/api/public/widget/pick': typeof ApiPublicWidgetPickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/widget/bar': typeof WidgetBarRoute
  '/api/public/verify-install': typeof ApiPublicVerifyInstallRoute
  '/api/public/widget/click': typeof ApiPublicWidgetClickRoute
  '/api/public/widget/pick': typeof ApiPublicWidgetPickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/dashboard'
    | '/leaderboard'
    | '/widget/bar'
    | '/api/public/verify-install'
    | '/api/public/widget/click'
    | '/api/public/widget/pick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/dashboard'
    | '/leaderboard'
    | '/widget/bar'
    | '/api/public/verify-install'
    | '/api/public/widget/click'
    | '/api/public/widget/pick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/widget/bar'
    | '/api/public/verify-install'
    | '/api/public/widget/click'
    | '/api/public/widget/pick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WidgetBarRoute: typeof WidgetBarRoute
  ApiPublicVerifyInstallRoute: typeof ApiPublicVerifyInstallRoute
  ApiPublicWidgetClickRoute: typeof ApiPublicWidgetClickRoute
  ApiPublicWidgetPickRoute: typeof ApiPublicWidgetPickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/bar': {
      id: '/widget/bar'
      path: '/widget/bar'
      fullPath: '/widget/bar'
      preLoaderRoute: typeof WidgetBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/verify-install': {
      id: '/api/public/verify-install'
      path: '/api/public/verify-install'
      fullPath: '/api/public/verify-install'
      preLoaderRoute: typeof ApiPublicVerifyInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/pick': {
      id: '/api/public/widget/pick'
      path: '/api/public/widget/pick'
      fullPath: '/api/public/widget/pick'
      preLoaderRoute: typeof ApiPublicWidgetPickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/click': {
      id: '/api/public/widget/click'
      path: '/api/public/widget/click'
      fullPath: '/api/public/widget/click'
      preLoaderRoute: typeof ApiPublicWidgetClickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WidgetBarRoute: WidgetBarRoute,
  ApiPublicVerifyInstallRoute: ApiPublicVerifyInstallRoute,
  ApiPublicWidgetClickRoute: ApiPublicWidgetClickRoute,
  ApiPublicWidgetPickRoute: ApiPublicWidgetPickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
