/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetBarRouteImport } from './routes/widget.bar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicVerifyInstallRouteImport } from './routes/api/public/verify-install'
import { Route as ApiPublicWidgetPickRouteImport } from './routes/api/public/widget.pick'
import { Route as ApiPublicWidgetHeartbeatRouteImport } from './routes/api/public/widget.heartbeat'
import { Route as ApiPublicWidgetClickRouteImport } from './routes/api/public/widget.click'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetBarRoute = WidgetBarRouteImport.update({
  id: '/widget/bar',
  path: '/widget/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicVerifyInstallRoute = ApiPublicVerifyInstallRouteImport.update({
  id: '/api/public/verify-install',
  path: '/api/public/verify-install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetPickRoute = ApiPublicWidgetPickRouteImport.update({
  id: '/api/public/widget/pick',
  path: '/api/public/widget/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetHeartbeatRoute =
  ApiPublicWidgetHeartbeatRouteImport.update({
    id: '/api/public/widget/heartbeat',
    path: '/api/public/widget/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWidgetClickRoute = ApiPublicWidgetClickRouteImport.update({
  id: '/api/public/widget/click',
  path: '/api/public/widget/click',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/network': typeof NetworkRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/widget/bar': typeof WidgetBarRoute
  '/api/public/verify-install': typeof ApiPublicVerifyInstallRoute
  '/api/public/widget/click': typeof ApiPublicWidgetClickRoute
  '/api/public/widget/heartbeat': typeof ApiPublicWidgetHeartbeatRoute
  '/api/public/widget/pick': typeof ApiPublicWidgetPickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/network': typeof NetworkRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/widget/bar': typeof WidgetBarRoute
  '/api/public/verify-install': typeof ApiPublicVerifyInstallRoute
  '/api/public/widget/click': typeof ApiPublicWidgetClickRoute
  '/api/public/widget/heartbeat': typeof ApiPublicWidgetHeartbeatRoute
  '/api/public/widget/pick': typeof ApiPublicWidgetPickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/network': typeof NetworkRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/widget/bar': typeof WidgetBarRoute
  '/api/public/verify-install': typeof ApiPublicVerifyInstallRoute
  '/api/public/widget/click': typeof ApiPublicWidgetClickRoute
  '/api/public/widget/heartbeat': typeof ApiPublicWidgetHeartbeatRoute
  '/api/public/widget/pick': typeof ApiPublicWidgetPickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/leaderboard'
    | '/network'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/dashboard'
    | '/widget/bar'
    | '/api/public/verify-install'
    | '/api/public/widget/click'
    | '/api/public/widget/heartbeat'
    | '/api/public/widget/pick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/leaderboard'
    | '/network'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/dashboard'
    | '/widget/bar'
    | '/api/public/verify-install'
    | '/api/public/widget/click'
    | '/api/public/widget/heartbeat'
    | '/api/public/widget/pick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/leaderboard'
    | '/network'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/widget/bar'
    | '/api/public/verify-install'
    | '/api/public/widget/click'
    | '/api/public/widget/heartbeat'
    | '/api/public/widget/pick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NetworkRoute: typeof NetworkRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WidgetBarRoute: typeof WidgetBarRoute
  ApiPublicVerifyInstallRoute: typeof ApiPublicVerifyInstallRoute
  ApiPublicWidgetClickRoute: typeof ApiPublicWidgetClickRoute
  ApiPublicWidgetHeartbeatRoute: typeof ApiPublicWidgetHeartbeatRoute
  ApiPublicWidgetPickRoute: typeof ApiPublicWidgetPickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/bar': {
      id: '/widget/bar'
      path: '/widget/bar'
      fullPath: '/widget/bar'
      preLoaderRoute: typeof WidgetBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/verify-install': {
      id: '/api/public/verify-install'
      path: '/api/public/verify-install'
      fullPath: '/api/public/verify-install'
      preLoaderRoute: typeof ApiPublicVerifyInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/pick': {
      id: '/api/public/widget/pick'
      path: '/api/public/widget/pick'
      fullPath: '/api/public/widget/pick'
      preLoaderRoute: typeof ApiPublicWidgetPickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/heartbeat': {
      id: '/api/public/widget/heartbeat'
      path: '/api/public/widget/heartbeat'
      fullPath: '/api/public/widget/heartbeat'
      preLoaderRoute: typeof ApiPublicWidgetHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/click': {
      id: '/api/public/widget/click'
      path: '/api/public/widget/click'
      fullPath: '/api/public/widget/click'
      preLoaderRoute: typeof ApiPublicWidgetClickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  NetworkRoute: NetworkRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WidgetBarRoute: WidgetBarRoute,
  ApiPublicVerifyInstallRoute: ApiPublicVerifyInstallRoute,
  ApiPublicWidgetClickRoute: ApiPublicWidgetClickRoute,
  ApiPublicWidgetHeartbeatRoute: ApiPublicWidgetHeartbeatRoute,
  ApiPublicWidgetPickRoute: ApiPublicWidgetPickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
